### ISSUE TITLE
[WELLDONE CODE] Connect to WellDone Code Extension in Remix Doesn't Work

### ISSUE THREAD

**Issue by futjrnaut** [welldonestudio/welldonestudio.github.io#38]
**Describe the issue**

The Connect to Welldone Code button doesn't do anything 
![image](https://user-images.githubusercontent.com/58874935/236614914-d183498b-9f5a-4803-8677-8ca0fdab5cbc.png)

**Expected behavior**

CLick the button, connect to the extension
**Additional context**

Brave Browser Win10 no shields

**Comment by SupersStone** [comment]
Need to open the developer mode in the settings
